username: git
year: 2025
semester: s3
gitpath: "{username}@git.cri.epita.fr:p/{year}-{semester}-tp/tp{nb:02d}-{student}"
path: "tp{nb:02d}"
project_dir: "tp{nb:02d}-{student}"

global_allowed_files: # readme are allowed internally, no need to put them here
  - .gitignore

tps:
  tp01:
    archi:
      - AUTHORS

  tp02:
    archi:
      - AUTHORS
      - facto:
        - facto.c
        - facto.h
        - main.c
      - fibo:
        - fibo.c
        - fibo.h
        - main.c
      - isqrt:
        - isqrt.c
        - isqrt.h
        - main.c
      - power_of_two:
        - power_of_two.c
        - power_of_two.h
        - main.c
      - digit_count:
        - digit_count.c
        - digit_count.h
        - main.c
      - divisor_sum:
        - divisor_sum.c
        - divisor_sum.h
        - main.c
      - perfect_numbers:
        - divisor_sum.h
        - is_perfect_number.c
        - is_perfect_number.h
        - main.c